[build]
  command = "npm install --platform=linux --arch=x64 @rollup/rollup-linux-x64-gnu && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
