[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
<<<<<<< HEAD
  status = 200 
=======
  status = 200

[build.environment]
  NODE_VERSION = "18" 
>>>>>>> cbabc0a5850ca5786bf5c5fd461dc15c87062100
